Point `node_modules/bs-platform` to `melange` to disguise `melange` as `bsb`
melange-re/melange-esy-template pull request #3
Opened 2021-06-10 11:31 UTC by jayesh-bhoot

Would you be willing to merge this change? I would rather have this in the original template instead of maintaining a fork.

2021-06-12 11:02 UTC, jchavarri requested changes
Thanks for this contribution! ✨ 

Please take a look at the requested changes, let me know what you think :)

2021-06-12 11:02 UTC, jchavarri commented on .gitignore
> +esy.lock
I don't think we want to ignore `esy.lock` folder, checking this folder in git makes sure everyone has the same versions of everything.

2021-06-12 11:02 UTC, jchavarri commented on README.md
> +1. generates a symbolically linked dir `bs-platform` in `node_modules`, which effectively makes `melange` the compiler behind the old `bsb` command, and then
```suggestion
1. generates a symbolically linked dir `bs-platform` in `node_modules`, which is helpful when using JavaScript bundlers like Webpack that expect to find Melange stdlib JavaScript files under `node_modules/bs-platform`.
```

2021-06-12 11:02 UTC, jchavarri commented on README.md
> +2. builds the project using the symbolically linked `bsb` command.
```suggestion
2. builds the project.
```

2021-06-12 11:35 UTC, jayesh-bhoot commented on .gitignore
> +esy.lock
Wasn't aware of this. I have pushed a commit to this effect.

2021-06-13 13:59 UTC, jchavarri approved these changes
Thanks!

2021-06-13 13:59 UTC, merged